### PR TITLE
1.6.0 Release

### PR DESCRIPTION
**Pull request by nprizal**
### PR List
- #72 (Includes #68)
- #75

### Diff
https://github.com/buildkite/test-collector-javascript/compare/v1.5.0...23d9de5ffe908b517288ff1475aa7e624a754848

### Validation
I have verified that all collectors send the result to Buildkite Test Analytics.
Screenshot 2023-10-06 at 12 08 31 PM

### CODE REVIEW

**Review by niceking — APPROVED** [review]
🚢

**Comment by tjschuck** [comment]
@nprizal This release doesn't seem to include any of the Playwright code 🙈  Check it out at https://www.npmjs.com/package/buildkite-test-collector/v/1.6.0?activeTab=code

Based on the tests being missing from the release as well, it would seem that you use some sort of release script that strips out unnecessary files.  It probably needs to be updated to include the `playwright/` dir.

**Comment by tjschuck** [comment]
^ Should be fixed by https://github.com/buildkite/test-collector-javascript/pull/77

**Comment by nprizal** [comment]
@tjschuck 

Thank you for bringing this to my attention and apologize for the oversight. I've looked at your fix, and that exactly what we have to do. I'll publish the release this morning and keep you updated.

**Pull request merged**
