### PR TITLE
Added jasmine and mocha reporters to npm package.

### PR DESCRIPTION
**Pull request by rmagrin**
The jasmine and mocha reporters were not being included in the npm package.

### CODE REVIEW

**Comment by mariovisic** [comment]
Looks good, but you also commited some changes to `util/tracer.test.js` as well ?

**Comment by mariovisic** [comment]
Thanks for picking this up 👍

**Comment by rmagrin** [comment]
> Looks good, but you also commited some changes to `util/tracer.test.js` as well ?

There was some flakiness in the tests that made the first execution fail. I just changed the `util/tracer.test.js` to see if it fixed the flakiness issue.

I can remove the test changes if needed.

**Comment by rmagrin** [comment]
@mariovisic do you have any more comments here?

**Comment by mariovisic** [comment]
no sorry, i'm not the maintainer, so you'll need to have someone from Buildkite review this. Though just looking you still have made changes to `util/tracer.test.js` which are unrelated, so maybe split these into another PR to make it easier to review, or add some rationale to your description in the PR about these changes.

**Comment by mariovisic** [comment]
oh sorry, missed the comment above about your change, makes sense, but yeah, you'll need to get someone from Buildkite to review 👍

**Comment by swebb** [comment]
Hi @rmagrin. Sorry for the delay. Thank you for the contribution. I'll raise a ticket for this and we'll see if we can get it merged.

**Review by KatieWright26 — APPROVED** [review]
Hi @rmagrin, thanks for your contribution! I'm going to merge your PR now, and your changes will go out in a release shortly.

**Pull request merged**
