### PR TITLE
Guard against possibility of test.err.multiple being undefined in mocha reporter

### PR DESCRIPTION
**Pull request by laurieboyes**
When using this reporter when running tests with [mocha-parallel-tests](https://www.npmjs.com/package/mocha-parallel-tests), differences in the `err` object cause an error that prevents the tests being reported. See issue https://github.com/buildkite/test-collector-javascript/issues/57 for an example.

```
// err object in mocha
AssertionError [ERR_ASSERTION]: 41 == 42
    at Context.<anonymous> (test.js:11:12)
    at process.processImmediate (node:internal/timers:471:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: '41',
  expected: '42',
  operator: '==',
  multiple: [Array]
}

// err object in mocha-parallel-tests
{
  message: '41 == 42',
  name: 'AssertionError',
  stack: 'AssertionError [ERR_ASSERTION]: 41 == 42\n' +
    '    at Context.<anonymous> (test.js:11:12)\n' +
    '    at process.processImmediate (node:internal/timers:471:21)'
}
```

This change removes the expectation that the `err.multiple` property will always be present and prevents the error.

### CODE REVIEW

**Comment by nprizal** [comment]
Hi @laurieboyes, thanks for looking into this issue.
I was able to reproduce the issue by running the test using `mocha-parallel-tests`. The interface of `err` object is different when you run the test with `mocha` and `mocha-parallel-tests`.

```
// err object in mocha
AssertionError [ERR_ASSERTION]: 41 == 42
    at Context.<anonymous> (test.js:11:12)
    at process.processImmediate (node:internal/timers:471:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: '41',
  expected: '42',
  operator: '==',
  multiple: [Array]
}

// err object in mocha-parallel-tests
{
  message: '41 == 42',
  name: 'AssertionError',
  stack: 'AssertionError [ERR_ASSERTION]: 41 == 42\n' +
    '    at Context.<anonymous> (test.js:11:12)\n' +
    '    at process.processImmediate (node:internal/timers:471:21)'
}
```

I digged into `mocha-parallel-tests` internal, and found [this line of code](https://github.com/mocha-parallel/mocha-parallel-tests/blob/d1b2e88fa6bad71d0a5d7487809fcb4be4030b9d/src/subprocess/reporter.ts#L128) that overrides `mocha` err object implementation. 

That being said, your changes look good to me and align with what mocha does internally. Can you update your PR description to add more context about `mocha-parallel-tests`?

**Comment by laurieboyes** [comment]
Thanks @nprizal, I’ve frankensteined your comment into my PR description. I’ll add my original description here for the record:

> We encountered this error from the mocha test collector in one of our e2e test suites a while ago: https://github.com/buildkite/test-collector-javascript/issues/57
> 
> After giving this some more attention, we discovered that the error was occurring when the `EVENT_TEST_END` event being handled in the reporter didn’t have a `err.multiple` property. The reporter assumes that this exists and is an array, and passes it to `failureExpanded`, which attempts to call `.map` on it ([src](https://github.com/buildkite/test-collector-javascript/blob/main/util/failureExpanded.js#L2)), and this is where our error occurred.
> 
> We haven’t quite reached an understanding of what is the expected schema of this event, but have spotted that in mocha’s base reporter, they guard against the possibility of this property being undefined ([src](https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L246)) so it seems reasonable to do the same here. When we tried this out, it solved our problem.
>

**Comment by nprizal** [comment]
Thanks @laurieboyes. Also, one of the test timed out even after several retries. This happens on the `origin/main` as well. I have increased the timeout on this [PR](https://github.com/buildkite/test-collector-javascript/pull/69) and merged it to `main`. Can you merge `origin/main` to your branch?

**Review by nprizal — APPROVED** [review]
Thanks @laurieboyes

**Pull request merged**
