### PR TITLE
Jasmine HTTP instrumentation

### PR DESCRIPTION
**Pull request by mariovisic**
Instrument HTTP calls for the Jasmine reporter, code is taken from PR #9 

This was really straightforward in Jasmine to get working as we can easily attach a tracer and network object to each test instance and then report on it later :)

I will rebase these changes once #32 is merged

### CODE REVIEW

**Comment by AeroCross** [comment]
👍, pending #32 being merged and this being rebased. Will approve formally once that's done.

**Comment by AeroCross** [comment]
Ready to rebase!

**Comment by mariovisic** [comment]
ready to go @AeroCross  👍

**Review by AeroCross — APPROVED** [review]
Thank you for your work, @mariovisic! 👏

**Pull request merged**
